Models/ErrorViewModel.cs
using System;

namespace SqrtRoot.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SqrtRoot.Models;

namespace SqrtRoot.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

         public IActionResult SqrtRoot()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/SqrtController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SqrtRoot.Models;

namespace SqrtRoot.Controllers
{
    public class SqrtController : Controller
    {
        public ActionResult SqrtRoot(){
            return View();
        }

        [HttpPost]
        public ActionResult SqrtRoot(int firstNumber, int secondNumber)
        {

        
            if ((firstNumber > 0) && (secondNumber > 0) && (firstNumber != secondNumber)){
           double sqrt = 0;
           double large = 0.0;

           double sqrtNum1 = Math.Sqrt(firstNumber);
           double sqrtNum2 = Math.Sqrt(secondNumber);

           if(sqrtNum1 > sqrtNum2){
               sqrt = sqrtNum1;
                large = firstNumber;
           }
           else
           {
               sqrt = sqrtNum2;
               large = secondNumber;
           }
           ViewBag.Sqrt = sqrt;
           ViewBag.Large = large;
            return View();
            
            }
            
         else if ((firstNumber < 0) && (secondNumber < 0)){
            ViewBag.Error = "Please input a positive number";
            return View();
        }

         else if (firstNumber == secondNumber){
            ViewBag.Same = "Numbers entered cannot be equal";
            return View();
        }
        //    double Num1 = double.Parse(firstNumber);
        //    double Num2 = double.Parse(secondNumber);

        else{
            return View();
        }
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SqrtRoot</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SqrtRoot</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - SqrtRoot - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Sqrt/SqrtRoot.cshtml

@{
    ViewData["Title"] = "Square Root Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>This simple program will take two numbers from the users and display the highest Square Root.</p>
    <p>Please Note a negative value will not run</p>
</div>

<div class="container border">
    <form method="post" asp-controller="Sqrt" asp-action="SqrtRoot">
            <div class="row form-group">
            <div class="col-4" >
                <label>Please Enter first Number</label>
            </div>  
        </div>
        <div class="col-6" >
            <input  type="number" required class="form-control" name="firstNumber" placeholder="Please Enter first Number"/>
            
        </div>

        <div class="col-4" >
                <label>Please Enter Second Number</label>
        </div>
        <div class="col-6"  >
            <input type="number" required class="form-control" name="secondNumber" placeholder="Please Enter Second Number"/>
        </div>
           <span class="text-danger">@ViewBag.Error</span>
           <span class="text-danger">@ViewBag.Same</span>
                @{
                   if (ViewBag.Sqrt != null)
                   {
                   <div>
                    <p class="text-success">The Number with the highest square root is @ViewBag.Large and the square root of @ViewBag.Large is @ViewBag.Sqrt</p>
                   </div>
                    }
                } 
         <div class="col-6 offset-4">
            <input type="submit" class="btn btn-primary form-control" name="secondNumber" placeholder="Please Enter Second Number"/>
        </div>
    </form>
   

        
    </div>

